jobs:
  sync:
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r .github/scripts/requirements.txt

      - name: Parse commit message
        id: parse-commit
        run: |
          OUTPUT=$(python .github/scripts/commit_parser.py "$COMMIT_MSG")
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          
      - name: Error Handling
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              body: `⚠️ 提交消息解析失败: ${process.env.COMMIT_MSG}`
            })